(defun loading (file)
  (format t "now loading ~a~%" file)
  (load file)
  (format t "success~%")
)

(defmacro make-table (table)
  (format t "#############################~%")
  (format t "now creating ~a~%" table)
  (format t "#############################~%")
  `(,table)
)

(loading "library.lisp")
(loading "Module/Code.lisp")
(loading "Module/Symbol.lisp")
(loading "Module/Parser.lisp")
(loading "Module/Table.lisp")

(make-table jump-mnemonic-table)
(make-table dest-mnemonic-table)
(make-table comp-mnemonic-table)
(make-table symbol-table)
(make-table rom-table)
